import type { Service } from '~/components/shared/types'

export default defineEventHandler((): Service[] => {
  return [
    {
      id: 1,
      slug: 'home-cleaning',
      title: 'Home Cleaning',
      category: 'home-care',
      description: 'Reliable, premium cleaning for modern homes.',
      longDescription: 'A consistent home cleaning service designed for routine upkeep, cleaner presentation, and less friction in daily living.',
      priceFrom: 250000,
      rating: 4.9,
      duration: '2–3 hours',
      image: '/images/services/home-cleaning.jpg',
      tags: ['Routine', 'Residential', 'Popular'],
      features: ['Surface dusting', 'Floor vacuuming', 'Kitchen reset', 'Bathroom wipe-down']
    },
    {
      id: 2,
      slug: 'laundry-pickup',
      title: 'Laundry Pickup',
      category: 'laundry',
      description: 'Fast pickup and neatly finished garments.',
      longDescription: 'A convenient pickup and return experience for users who want a simpler and more polished laundry flow.',
      priceFrom: 50000,
      rating: 4.8,
      duration: 'Same day / next day',
      image: '/images/services/laundry-pickup.jpg',
      tags: ['Pickup', 'Convenient'],
      features: ['Pickup scheduling', 'Garment handling', 'Clean return']
    },
    {
      id: 3,
      slug: 'deep-cleaning',
      title: 'Deep Cleaning',
      category: 'deep-cleaning',
      description: 'A complete reset for move-ins, seasonal cleaning, and intensive care.',
      longDescription: 'A more comprehensive service for homes that need a full reset rather than a lighter maintenance pass.',
      priceFrom: 650000,
      rating: 4.9,
      duration: '3–5 hours',
      image: '/images/services/deep-cleaning.jpg',
      tags: ['Premium', 'Reset', 'Detailed'],
      features: ['Room-by-room reset', 'Bathroom detail', 'Kitchen deep wipe', 'Final finishing pass']
    },
    {
      id: 4,
      slug: 'office-upkeep',
      title: 'Office Upkeep',
      category: 'business',
      description: 'Structured cleaning support for workspaces and operational areas.',
      longDescription: 'Built for recurring office maintenance with a more reliable and organized request flow.',
      priceFrom: 900000,
      rating: 4.8,
      duration: 'Custom schedule',
      image: '/images/hero/tidy-hero-1.jpg',
      tags: ['Business', 'Recurring'],
      features: ['Work area upkeep', 'Shared-space reset', 'Structured scheduling']
    },
    {
      id: 5,
      slug: 'move-in-reset',
      title: 'Move-In Reset',
      category: 'deep-cleaning',
      description: 'A tailored reset package for newly occupied spaces.',
      longDescription: 'A cleaner onboarding service for new tenants or owners who want their space fully reset before use.',
      priceFrom: 850000,
      rating: 4.9,
      duration: '4–6 hours',
      image: '/images/hero/tidy-hero-2.jpg',
      tags: ['Move-in', 'Premium'],
      features: ['Deep reset', 'Dust removal', 'Bathroom prep', 'Kitchen prep']
    },
    {
      id: 6,
      slug: 'sofa-refresh',
      title: 'Sofa Refresh',
      category: 'specialty',
      description: 'Targeted upholstery care for cleaner, fresher seating.',
      longDescription: 'A focused service for upholstery refresh and presentation improvement.',
      priceFrom: 300000,
      rating: 4.7,
      duration: '1–2 hours',
      image: '/images/hero/tidy-hero-3.jpg',
      tags: ['Upholstery', 'Specialty'],
      features: ['Surface refresh', 'Targeted attention', 'Material-safe handling']
    },
    {
      id: 7,
      slug: 'mattress-care',
      title: 'Mattress Care',
      category: 'specialty',
      description: 'Specialized care for cleaner, more refreshed bedding surfaces.',
      longDescription: 'A focused specialty service intended to improve cleanliness and comfort perception.',
      priceFrom: 350000,
      rating: 4.8,
      duration: '1–2 hours',
      image: '/images/services/home-cleaning.jpg',
      tags: ['Bedroom', 'Specialty'],
      features: ['Surface care', 'Detail handling', 'Cleaner finish']
    },
    {
      id: 8,
      slug: 'iron-and-fold',
      title: 'Iron & Fold',
      category: 'laundry',
      description: 'A simpler garment finishing service for daily convenience.',
      longDescription: 'For users who want better garment presentation without the complexity of a full custom flow.',
      priceFrom: 70000,
      rating: 4.7,
      duration: 'Scheduled turnaround',
      image: '/images/services/laundry-pickup.jpg',
      tags: ['Laundry', 'Daily'],
      features: ['Garment finishing', 'Folded return', 'Simple scheduling']
    },
    {
      id: 9,
      slug: 'post-event-cleanup',
      title: 'Post-Event Cleanup',
      category: 'business',
      description: 'A stronger reset flow for spaces after gatherings or operations peaks.',
      longDescription: 'Useful for event spaces, private gatherings, or operational recovery when presentation matters.',
      priceFrom: 1200000,
      rating: 4.8,
      duration: 'Custom duration',
      image: '/images/services/deep-cleaning.jpg',
      tags: ['Event', 'Recovery'],
      features: ['Waste collection', 'Surface reset', 'Detailed recovery']
    },
    {
      id: 10,
      slug: 'kitchen-detail-reset',
      title: 'Kitchen Detail Reset',
      category: 'deep-cleaning',
      description: 'A focused kitchen reset for heavier buildup and daily-use recovery.',
      longDescription: 'Designed for kitchens that need more than a quick wipe-down, with stronger attention on surface condition and freshness.',
      priceFrom: 420000,
      rating: 4.8,
      duration: '2–3 hours',
      image: '/images/hero/tidy-hero-1.jpg',
      tags: ['Kitchen', 'Detailed'],
      features: ['Counter reset', 'Exterior appliance wipe', 'Sink area care', 'Surface finishing']
    },
    {
      id: 11,
      slug: 'bathroom-deep-reset',
      title: 'Bathroom Deep Reset',
      category: 'deep-cleaning',
      description: 'A premium deep-cleaning pass for bathroom spaces that need extra attention.',
      longDescription: 'Built for users who want a more complete refresh of bathroom surfaces and presentation.',
      priceFrom: 380000,
      rating: 4.8,
      duration: '1–2 hours',
      image: '/images/hero/tidy-hero-2.jpg',
      tags: ['Bathroom', 'Reset'],
      features: ['Surface care', 'Mirror cleaning', 'Fixture wipe-down', 'Final finishing']
    },
    {
      id: 12,
      slug: 'weekly-home-care',
      title: 'Weekly Home Care',
      category: 'home-care',
      description: 'A recurring service option for households that want consistency.',
      longDescription: 'For returning customers who want lighter friction and more reliable ongoing home maintenance.',
      priceFrom: 220000,
      rating: 4.9,
      duration: '2–3 hours',
      image: '/images/services/home-cleaning.jpg',
      tags: ['Recurring', 'Weekly'],
      features: ['Routine upkeep', 'Repeat-friendly flow', 'Cleaner scheduling']
    },
    {
      id: 13,
      slug: 'curtain-refresh',
      title: 'Curtain Refresh',
      category: 'specialty',
      description: 'Specialized refresh for curtains and soft interior fabrics.',
      longDescription: 'A niche service that adds more realism to the catalog and broadens booking options.',
      priceFrom: 260000,
      rating: 4.7,
      duration: '1–2 hours',
      image: '/images/hero/tidy-hero-3.jpg',
      tags: ['Fabric', 'Specialty'],
      features: ['Fabric-safe handling', 'Refresh pass', 'Presentation improvement']
    },
    {
      id: 14,
      slug: 'carpet-refresh',
      title: 'Carpet Refresh',
      category: 'specialty',
      description: 'A targeted care service for carpets and high-contact floor fabric areas.',
      longDescription: 'Helps the catalog feel more complete by adding a realistic specialty care option.',
      priceFrom: 340000,
      rating: 4.8,
      duration: '1–2 hours',
      image: '/images/services/deep-cleaning.jpg',
      tags: ['Floor Care', 'Specialty'],
      features: ['Surface refresh', 'Targeted treatment', 'Cleaner finish']
    },
    {
      id: 15,
      slug: 'pantry-organization',
      title: 'Pantry Organization',
      category: 'home-care',
      description: 'A light organization service for cleaner kitchen storage flow.',
      longDescription: 'A more lifestyle-oriented service that helps the platform feel broader and more modern.',
      priceFrom: 280000,
      rating: 4.7,
      duration: '1–2 hours',
      image: '/images/hero/tidy-hero-2.jpg',
      tags: ['Organization', 'Lifestyle'],
      features: ['Shelf organization', 'Visual reset', 'Storage alignment']
    }
  ]
})