import type { Service } from '~/components/shared/types'

export default defineEventHandler((): Service[] => {
  return [
    {
      id: 1,
      slug: 'home-cleaning',
      title: 'Pembersihan Rumah',
      category: 'home-care',
      description: 'Layanan pembersihan premium yang andal untuk rumah modern.',
      longDescription: 'Layanan pembersihan rumah yang konsisten, dirancang untuk perawatan rutin, tampilan yang lebih rapi, dan mengurangi hambatan dalam kehidupan sehari-hari.',
      priceFrom: 250000,
      rating: 4.9,
      duration: '2–3 jam',
      image: '/images/services/home-cleaning.jpg',
      tags: ['Rutin', 'Hunian', 'Populer'],
      features: ['Membersihkan debu permukaan', 'Vakum lantai', 'Penataan dapur', 'Pembersihan kamar mandi']
    },
    {
      id: 2,
      slug: 'laundry-pickup',
      title: 'Penjemputan Laundry',
      category: 'laundry',
      description: 'Penjemputan cepat dengan hasil pakaian yang rapi.',
      longDescription: 'Pengalaman penjemputan dan pengembalian yang praktis bagi pengguna yang menginginkan proses laundry yang lebih sederhana dan rapi.',
      priceFrom: 50000,
      rating: 4.8,
      duration: 'Hari yang sama / hari berikutnya',
      image: '/images/services/laundry-pickup.jpg',
      tags: ['Penjemputan', 'Praktis'],
      features: ['Penjadwalan penjemputan', 'Penanganan pakaian', 'Pengembalian bersih']
    },
    {
      id: 3,
      slug: 'deep-cleaning',
      title: 'Pembersihan Mendalam',
      category: 'deep-cleaning',
      description: 'Pembersihan menyeluruh untuk pindahan, musim tertentu, dan perawatan intensif.',
      longDescription: 'Layanan yang lebih komprehensif untuk rumah yang membutuhkan pembersihan total, bukan sekadar perawatan ringan.',
      priceFrom: 650000,
      rating: 4.9,
      duration: '3–5 jam',
      image: '/images/services/deep-cleaning.jpg',
      tags: ['Premium', 'Reset', 'Detail'],
      features: ['Pembersihan per ruangan', 'Detail kamar mandi', 'Pembersihan dapur mendalam', 'Finishing akhir']
    },
    {
      id: 4,
      slug: 'office-upkeep',
      title: 'Perawatan Kantor',
      category: 'business',
      description: 'Dukungan pembersihan terstruktur untuk ruang kerja dan area operasional.',
      longDescription: 'Dirancang untuk perawatan kantor secara berkala dengan alur permintaan yang lebih rapi dan dapat diandalkan.',
      priceFrom: 900000,
      rating: 4.8,
      duration: 'Jadwal fleksibel',
      image: '/images/hero/tidy-hero-1.jpg',
      tags: ['Bisnis', 'Berulang'],
      features: ['Perawatan area kerja', 'Penataan ruang bersama', 'Penjadwalan terstruktur']
    },
    {
      id: 5,
      slug: 'move-in-reset',
      title: 'Reset Pindahan',
      category: 'deep-cleaning',
      description: 'Paket pembersihan khusus untuk ruang yang baru ditempati.',
      longDescription: 'Layanan pembersihan awal untuk penyewa atau pemilik baru yang ingin ruangnya benar-benar bersih sebelum digunakan.',
      priceFrom: 850000,
      rating: 4.9,
      duration: '4–6 jam',
      image: '/images/hero/tidy-hero-2.jpg',
      tags: ['Pindahan', 'Premium'],
      features: ['Pembersihan menyeluruh', 'Penghilangan debu', 'Persiapan kamar mandi', 'Persiapan dapur']
    },
    {
      id: 6,
      slug: 'sofa-refresh',
      title: 'Penyegaran Sofa',
      category: 'specialty',
      description: 'Perawatan khusus upholstery untuk tempat duduk yang lebih bersih dan segar.',
      longDescription: 'Layanan khusus yang fokus pada penyegaran sofa dan peningkatan tampilan.',
      priceFrom: 300000,
      rating: 4.7,
      duration: '1–2 jam',
      image: '/images/hero/tidy-hero-3.jpg',
      tags: ['Upholstery', 'Khusus'],
      features: ['Penyegaran permukaan', 'Perawatan terfokus', 'Penanganan aman bahan']
    },
    {
      id: 7,
      slug: 'mattress-care',
      title: 'Perawatan Kasur',
      category: 'specialty',
      description: 'Perawatan khusus untuk permukaan kasur yang lebih bersih dan segar.',
      longDescription: 'Layanan khusus yang bertujuan meningkatkan kebersihan dan kenyamanan kasur.',
      priceFrom: 350000,
      rating: 4.8,
      duration: '1–2 jam',
      image: '/images/services/home-cleaning.jpg',
      tags: ['Kamar tidur', 'Khusus'],
      features: ['Perawatan permukaan', 'Penanganan detail', 'Hasil lebih bersih']
    },
    {
      id: 8,
      slug: 'iron-and-fold',
      title: 'Setrika & Lipat',
      category: 'laundry',
      description: 'Layanan finishing pakaian yang sederhana untuk kebutuhan harian.',
      longDescription: 'Untuk pengguna yang ingin tampilan pakaian lebih rapi tanpa proses yang kompleks.',
      priceFrom: 70000,
      rating: 4.7,
      duration: 'Sesuai jadwal',
      image: '/images/services/laundry-pickup.jpg',
      tags: ['Laundry', 'Harian'],
      features: ['Finishing pakaian', 'Pengembalian terlipat rapi', 'Penjadwalan sederhana']
    },
    {
      id: 9,
      slug: 'post-event-cleanup',
      title: 'Pembersihan Pasca Acara',
      category: 'business',
      description: 'Pembersihan intensif untuk ruang setelah acara atau aktivitas tinggi.',
      longDescription: 'Cocok untuk ruang acara, pertemuan pribadi, atau pemulihan operasional saat tampilan sangat penting.',
      priceFrom: 1200000,
      rating: 4.8,
      duration: 'Durasi fleksibel',
      image: '/images/services/deep-cleaning.jpg',
      tags: ['Acara', 'Pemulihan'],
      features: ['Pengumpulan sampah', 'Pembersihan permukaan', 'Pemulihan detail']
    }
  ]
})